# Generated by Django 5.1.2 on 2024-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('main_theme', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
