# Generated by Django 5.1.2 on 2024-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='child',
            field=models.ManyToManyField(to='child.child'),
        ),
    ]
