# Generated by Django 5.1.2 on 2024-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practice_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
