# Generated by Django 5.1.2 on 2024-12-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0006_alter_coach_extra_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Короткое название')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное название')),
                ('sport', models.CharField(max_length=50, verbose_name='Вид спорта')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coach.coach', verbose_name='Тренер')),
            ],
        ),
    ]
