# Generated by Django 5.1.2 on 2024-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=50)),
                ('main_sport', models.CharField(max_length=50)),
                ('extra_sport', models.CharField(max_length=50)),
                ('experience_date', models.SmallIntegerField()),
                ('practice', models.ManyToManyField(to='practice.practice')),
            ],
        ),
    ]
