# Generated by Django 5.1.2 on 2024-11-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='experience_date',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
