# Generated by Django 5.1.2 on 2024-11-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_alter_coach_experience_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
