# Generated by Django 5.1.2 on 2024-11-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_coach_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='experience_date',
            new_name='experience_years',
        ),
    ]
