# Generated by Django 5.1.2 on 2024-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_alter_coach_options_coach_patronymic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='extra_sport',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дополнительный вид спорта'),
        ),
    ]
