# Generated by Django 5.1.2 on 2024-12-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_coach_extra_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='practice',
        ),
    ]
